# Generated by Django 4.2.1 on 2024-05-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
