# Generated by Django 4.2.1 on 2024-05-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_userprofile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_buyer',
        ),
    ]
