# Generated by Django 4.2.1 on 2024-05-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_propertyphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
