# Generated by Django 4.2.1 on 2024-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_property_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Your Default City', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(default='Your Default Country', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(default='Your Default District', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='pincode',
            field=models.CharField(default='Your Default Pincode', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='Your Default State', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(default='Your Default Area', max_length=255),
        ),
    ]
