# Generated by Django 4.2.1 on 2024-05-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='rentals.property'),
        ),
    ]
